version: '3'
services:
  py:
    build: .
    ports:
      - "8080:8080"
  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepass

volumes:
  mongodb-data: